live_config_reload = true

import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window]
title = "Terminal"
startup_mode = "Windowed"
opacity = 0.75
padding = { x = 8, y = 8 }

[scrolling]
history = 10000

[font]
size = 16
normal = { family = "FiraCode Nerd Font", style = "Regular" }

